### ISSUE TITLE
Error: Unable to run your project.

### ISSUE THREAD

**Issue by NotMyself** [andrewlock/NetEscapades.Templates#1]
using the following commands:

```powershell
dotnet new basicwebapi --name "foodog" -A
dotnet restore
dotnet build
dotnet run
```
I get the following error on run:

```
Unable to run your project.
Please ensure you have a runnable project type and ensure 'dotnet run' supports this project.
The current OutputType is 'Exe'.
```

dotnet -info output:

```
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3
```

**Comment by andrewlock** [comment]
By default, the template will target both `net451` and `netcreapp1.1` so you need to tell `dotnet` which framework to target, for example `dotnet run -f netcoreapp1.1` (the .NET CLI error message is really unhelpful here...)

So, for your example, the following should work: 
```
dotnet new basicwebapi --name "foodog" -A
dotnet restore
dotnet build
dotnet run -f netcoreapp1.1
```

**Comment by andrewlock** [comment]
I think this will be a common problem, so I'll make a patch release that defaults to net core only instead of targeting both

**Comment by NotMyself** [comment]
Yep that was the catch for me.

**Comment by andrewlock** [comment]
I have just pushed a new version out. If you run `dotnet new --install "NetEscapades.Templates::*"` again, The template will default to .NET Core instead. 

Let me know if you find any other issues with it, thanks!
