### ISSUE TITLE
.net core 2.1 version

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [andrewlock/NetEscapades.Templates#2]
Hi,

it would be really nice if template can be upgrade to .net 2.1 rc1
I use it as a base for all SPA with backend in .net core and full framework and frontend in angular/vue
so thanks for great work

**Comment by andrewlock** [comment]
I just committed a .NET Core 2.1 version that uses Microsoft.AspNetCore.App - I've had it sat locally for a while and forgot to commit it, sorry!
